//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bludata.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PessoaSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PessoaSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bludata.Models.Resources.PessoaSql", typeof(PessoaSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	Pessoa.Codigo as PessoaCodigo,
        ///		Pessoa.Nome as PessoaNome,
        ///		Pessoa.Cpf as PessoaCpf,
        ///		Pessoa.Dt_nascimento as PessoaDataNascimento,
        ///		Pessoa.Dt_cadastro as PessoaDataCadastro,
        ///		Pessoa.Uf as UfCodigo,
        ///		Pessoa.Cliente as ClienteCodigo,
        ///		UfPessoa.Codigo as UfCodigo,
        ///		UfPessoa.Nome as UfNome,
        ///		UfPessoa.Cadastro as UfCadastro,
        ///		Cliente.Codigo as ClienteCodigo,
        ///		Cliente.Nome as ClienteNome,
        ///		Cliente.Uf as ClienteUf,
        ///		Cliente.Cnpj as ClienteCnpj,
        ///		UfCliente.Codigo as UfCodigo,
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListarPessoa {
            get {
                return ResourceManager.GetString("ListarPessoa", resourceCulture);
            }
        }
    }
}
